development:
  adapter: postgresql
  encoding: unicode
  database: dog_park_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dog_park_test
  pool: 5
  username:
  password:
